apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: rauto-workload-resource-template-65837
  project: mdp
spec: 
  contexts: 
  - name: rafay-configcontext
  hooks: {}
  provider: terraform
  repositoryOptions:
    branch: main
    directoryPath: terraform/resource_template
    name: mdp-csc-rafay
  variables:
  - name: cluster_name
    value: $(resource."rauto-eks-resource-template-65837".output.eks_cluster_name.value)$
    valueType: expression
  - name: postgres_host
    value: $(resource."rauto-rds-resource-template-65837".output.rds_hostname.value)$
    valueType: expression
  - name: postgres_username
    value: $(resource."rauto-rds-resource-template-65837".output.rds_username.value)$
    valueType: expression
  - name: postgres_password
    options:
    sensitive: true
    value: sealed://variables.3
    valueType: expression
  - name: redis_config_endpoint
    value: $(resource."rauto-ec-resource-template-65837".output.configuration_endpoint_address.value)$
    valueType: expression
    version: custom-noagent